var express = require('express')
var router = express.Router()
let cinema = require('../controllers/cinema')
// router.get('/findAll', cinema.findAll)
// router.post('/save', cinema.save)
// router.patch('/save')
router.route('/')
    .get(cinema.findAll)
    .post(cinema.save)
    .patch(cinema.updata)
    .delete(cinema.remove)
router.get('/findOne', cinema.findOne)
router.post('/search', cinema.search)
module.exports = router